/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: League Studio (https://sketchfab.com/leaguestudio)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/chesterfield-sofa-66ba4225efaa4de59d9a9b7086363199
title: chesterfield-sofa
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Sofa(props, { ref }) {
  const { nodes, materials } = useGLTF("./models/Sofa/sofaModel.glb");
  return (
    <group {...props} dispose={null} ref={ref}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.28}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.03}>
          <group scale={0.39}>
            <mesh
              geometry={nodes.sofa_geo_Leather_mat_0.geometry}
              material={materials.Leather_mat}
            />
            <mesh
              geometry={nodes.sofa_geo_Leather_mat_0_1.geometry}
              material={materials.Leather_mat}
            />
          </group>
          <group scale={0.39}>
            <mesh
              geometry={nodes.legs_geo4_wood_mat_0.geometry}
              material={materials.wood_mat}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/sofaModel.glb");
